# Blue Deployments (Versión Actual)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: appdevops
  labels:
    app: frontend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: app-frontend:blue
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  namespace: appdevops
  labels:
    app: backend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: app-backend:main
        ports:
        - containerPort: 5000
