# Backend Service (Blue-Green switching)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: appdevops
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
---
# Frontend Service (Blue-Green switching)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: appdevops
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort